USE [master]
GO

/****** Object:  Database [Star_security_Service]    Script Date: 3/3/2025 12:53:02 PM ******/
CREATE DATABASE [Star_security_Service]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Star_security_Service', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Star_security_Service.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Star_security_Service_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Star_security_Service_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Star_security_Service].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Star_security_Service] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Star_security_Service] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Star_security_Service] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Star_security_Service] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Star_security_Service] SET ARITHABORT OFF 
GO

ALTER DATABASE [Star_security_Service] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Star_security_Service] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Star_security_Service] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Star_security_Service] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Star_security_Service] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Star_security_Service] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Star_security_Service] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Star_security_Service] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Star_security_Service] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Star_security_Service] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Star_security_Service] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Star_security_Service] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Star_security_Service] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Star_security_Service] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Star_security_Service] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Star_security_Service] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Star_security_Service] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Star_security_Service] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Star_security_Service] SET  MULTI_USER 
GO

ALTER DATABASE [Star_security_Service] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Star_security_Service] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Star_security_Service] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Star_security_Service] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Star_security_Service] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Star_security_Service] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Star_security_Service] SET QUERY_STORE = ON
GO

ALTER DATABASE [Star_security_Service] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Star_security_Service] SET  READ_WRITE 
GO

